name: ${name}
description: ${description}
author: ${author}
main: ${mainClass}
version: ${version}
url: ${url}
commands:
  kazuya-utilities:
    usage: /<command> <reload>
    aliases: [kazu-u]
    description: "recarga el configuration.yml ."