name: ${name}
description: ${description}
author: ${author}
main: ${mainClass}
version: ${version}
url: ${url}
commands:
  example:
    aliases: ["ex"]
    description: "Plugin de Utilidades de Kazuya."